### ISSUE TITLE
add create geometry by points

### ISSUE THREAD

**Issue by aradermacher** [BAMresearch/amworkflow#10]
- [x] add function for creating geometry by points in geometry/composites_geometries.py and in the GeometryCenterline class. 
- [ ] Testing via example Truss  --> moved to issue #34 
- [x] new simpler one (as in Yuxiang's branch)
- [x] git action for wall example for different infill parameters via console by doit get_var 
- [x] add store points in csv file in GeometryOCC class
- [x] add example jupyter notebook for toy example

**Comment by aradermacher** [comment]
Hi Yuxiang, I saw that the trussarc example works now in this branch. Can we merge the branch into the main?

**Comment by aradermacher** [comment]
some comments:

- I agree to use is_close as global parameter for the GeometryCenterline Class.
- In geomtery.py I would like to import the CreateWallByPointsUpdate as "from amworkflow.geometry.composite_geometries import CreateWallByPointsUpdate " and call add in this way in the GeometryCenterline Class
-

**Comment by aradermacher** [comment]
On my vdi the example tooks quite a while, is that normal

**Comment by aradermacher** [comment]
Last comment: I checked the design and it looks like there are two holes missing:
OLD
![image](https://github.com/BAMresearch/amworkflow/assets/20766342/5ee52121-665a-414b-a334-04b335dc6548)
NEW:
![image](https://github.com/BAMresearch/amworkflow/assets/20766342/e8e99cd9-ea40-43d2-be37-4010c0e65011)

**Comment by YuXHe15** [comment]
Hi Annika, For now it is barely a simple replication from the branch v0.43 on which I haven't implemented the improvements of the new CAD module. I can finish the integration by next week.

I was actively changing parameters, trying to solve the problem when bending geometries, which may cause the error of missing holes. I ll look into this issue and fix it.

Therefore can we wait for several days for my updates?

**Comment by YuXHe15** [comment]
I think The long processing time is due to I disabled the multithreads in Gmsh in a previous Fix, because it is not compatible with Doit multithreads. Otherwise it should be faster considerably
