### ISSUE TITLE
jupyter notebook for example workflow

### ISSUE THREAD

**Issue by aradermacher** [BAMresearch/amworkflow#28]
There is a new jupyter hub server at BAM which we maybe could use to have something like a userfriendly interface to create and run workflows.

**Comment by YuXHe15** [comment]
That's a great idea! 

> There is a new jupyter hub server at BAM which we maybe could use to have something like a userfriendly interface to create and run workflows.

Great idea! I will start a draft on this jupyter notebook  this week.

**Comment by aradermacher** [comment]
I would wait until we have your paramwall example running in the main branch before starting the work on a jupyter notebook.

**Comment by aradermacher** [comment]
I will delete that issue for now
