### ISSUE TITLE
fix meshing with gmsh

### ISSUE THREAD

**Issue by aradermacher** [BAMresearch/amworkflow#7]
Topo solid required for gmsh meshing but Topo shape read by step file.

**Comment by aradermacher** [comment]
in the moment use Wall example (dodo_wall.py in examples/Wall) for testing

**Comment by aradermacher** [comment]
@YuXHe15 I added the solid_amker function and transfer the Topo_shape to Topo_solid in the meshing class, but the mesh creating still doesn't work. Could you please have a look.

**Comment by YuXHe15** [comment]
Hi Annika, yes I ll look into this issueOn 13. Oct 2023, at 08:28, aradermacher ***@***.***> wrote:﻿
@YuXHe15 I added the solid_amker function and transfer the Topo_shape to Topo_solid in the meshing class, but the mesh creating still doesn't work. Could you please have a look.
